trigger:
- dev

pool:
 vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.0.4'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cat <<EOF > output.tf
      output "azure_db_server_name" {
        value = azurerm_mssql_server.db_server.name
      }

      output "azure_db_name" {
        value = azurerm_mssql_database.db.name
      }

      output "queue_name" {
        value = azurerm_servicebus_queue.queue.name
      }
      EOF


- task: AzureCLI@2
  inputs:
    azureSubscription: 'epam-service-principal'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account show'