apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: django-frontend
        image: polyarush.azurecr.io/django-frontend
        ports:
        - containerPort: 8000
        env:
        - name: azure_db_name
          value: "#{azure_db_name}#"
        - name: DB_USER
          value: "#{DB_USER}#"
        - name: password
          value: "#{password}#"
        - name: azure_db_server_name
          value: "#{azure_db_server_name}#"
        - name: SERVICE_BUS_CONNECTION_STR
          value: "#{SERVICE_BUS_CONNECTION_STR}#"
        - name: SERVICE_BUS_QUEUE_NAME
          value: "#{SERVICE_BUS_QUEUE_NAME}#"
        - name: STRESS_MINS
          value: "1"
        - name: secret-command
          value: "#{secret-command}#"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 8000
